export const AUTH_REGISTER = "AUTH_REGISTER";
export const AUTH_ERROR = "AUTH_ERROR";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOGIN = "AUTH_LOGIN";
export const AUTH_CLEAR_ERROR = "AUTH_CLEAR_ERROR";
export const COLLECTION_GET_SECRET = "COLLECTION_GET_SECRET";
